//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTrips.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Trip
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="This Field is Mandatory to fill")]
        public string Name { get; set; }
        [Required(ErrorMessage = "This Field is Mandatory to fill")]
        public string Destination { get; set; }
        public Nullable<int> Year { get; set; }
        public string Month { get; set; }
    }
}
